modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Furnace%20Recycle"
logoFile="icon.png"

[[mods]]
modId="furnacerecycle"
version="2.5"
displayName="Furnace Recycle"
displayURL="https://serilum.com/mod/furnace-recycle"
authors="Rick South"
description='''Makes all metal-containing items in the game recyclable in a furnace.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.furnacerecycle]]
    modId="collective"
    mandatory=true
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.furnacerecycle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"
